#!/bin/bash

make > /dev/null

#/usr/bin/time -f "%E %Uu %Ss %P" ./target/crossw data/Crossword$1.txt -dict data/Words.txt -draw
#gdb --args ./target/crossw data/Crossword$1.txt -dict data/Words.txt
#valgrind ./target/crossw data/Crossword$1.txt -dict data/Words.txt
/usr/bin/time -f "%E %Uu %Ss %P" ./target/crossw data/Empty7.txt -dict data/Words.txt

make clean > /dev/null
