#!/bin/bash

make > /dev/null

valgrind ./target/crossw data/Crossword$1.txt -dict data/MoreWords.txt # | grep "refs:"
# callgrind_annotate > profiler.out
# rm -rf callgrind.out.*

# --dsymutil=yes --tool=callgrind
make clean > /dev/null
